[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:production"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "disaster-prep-app"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "5000"
REACT_APP_API_URL = "${{RAILWAY_STATIC_URL}}"
