[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node railway-server.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "disaster-prep-app"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "5000"
