[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:production"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "disaster-prep-app"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "5000"
