[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "disaster-prep-app"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "5000"
REACT_APP_API_URL = "https://disaster-prep-app-production.up.railway.app/api"
